rly_file = "Arun_Valley_Line.rly"
ttb_files = [ "Arun_Valley_Line_2026-03-04.ttb",]
ssn_files = [ "Arun_Valley_Line_Initial_Session.ssn",]
img_files = [ "Arun_Valley_Line.bmp",]
doc_files = [ "Arun_Valley_Line.md",]
release_date = "2026-02-26"
version = "1.0.0"
country_code = "GB"
factual = true
description = ""
year = 2026
display_name = "Arun Valley Line"
name = "Arun Valley Line"
signal_position = "left"
author = "Oxalin1"
contributors = []
